---
- name: "Setting up chrony client"
  hosts: ntpclient
  become: yes
  tasks:
    - name: Update chrony package
      yum:
        name: chrony
        state: latest

    - name: Comment out server lines
      lineinfile:
        path: "/etc/chrony.conf"
        regexp: '^server'
        state: absent

    - name: Add NTP1 server IP
      lineinfile:
        path: "/etc/chrony.conf"
        line: 'server 192.168.33.25 iburst'

    - name: Add NTP2 server IP
      lineinfile:
        path: "/etc/chrony.conf"
        line: 'server 192.168.33.26 iburst'

    - name: Restart the service
      service:
        name: chronyd
        state: restarted
~                          
